# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 离患小站
subtitle: '明天会更好吗'
description: '个人博客'
keywords: 
author: dsk
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://dskblog.top
permalink: :title.html
permalink_defaults:
root: /
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy: 
- type: netlify
  token: nfp_MZzZs3CshVVxDheeQBdYE7LGUmovQRDTc34c
  site_id: c42a1b21-9378-4f7b-97d2-9c109f86c65c



search:
  path: search.xml
  field: post
  content: true
  template: 
aplayer:
  meting: true
  asset_inject: false
  # Artitalk
  # see https://artitalk.js.org/
artitalk: #lencloud说说
    enable: false
    appId:
    appKey:
    path:
    js:
    option:
    front_matter:
# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
# Security
encrypt: # hexo-blog-encrypt
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码.
  tags:
  - {name: tagName, password: 密码A}
  - {name: tagName, password: 密码B}
  theme: xray
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.
hexo-daily-news:
  enable: true
  apiUrl: 'https://v2.alapi.cn/api/zaobao'
  token: 'a3dksvxt73gyhpp3gjymbxxcsoqjq9'
version: '1.0.0'
timestamp: <%= new Date().getTime() %>
live_reload:
    delay: 0
    info: true
    retry: 3000
sitemap:
    path: sitemap.xml
webPushNotification:
  webpushrKey: "249649ce5b1ad27d14106506b2465364"
  webpushrAuthToken: "105674"
  trackingCode: "BJNGWXPB2ZzwJMvqv_rNqMl-Prl6AMj93NePtdH4sb5nNfw_wM5nD46cQyxC1QIdSSuUG1YnwRLnK4IbmFF7VP4"